Configure Bluebird before first use of Promise.
Turn browser_scripts#defaultScripts into a get property, so it's not executed when the file is being required. This to avoid:
Error: cannot enable long stack traces after promises have been created